// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrqvfkujhzhvgwmanwvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycXZma3VqaHpodmd3bWFud3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MjYwNjEsImV4cCI6MjA4NDQwMjA2MX0.MqqZAiO5YPR46-1N_D7N38jdw44ijLvjp7R8U5k3MCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});